# Plugin configuration
eval 
            fuck () {
                TF_PYTHONIOENCODING=$PYTHONIOENCODING;
                export TF_ALIAS=fuck;
                export TF_SHELL_ALIASES=$(alias);
                export TF_HISTORY="$(fc -ln -10)";
                export PYTHONIOENCODING=utf-8;
                TF_CMD=$(
                    thefuck THEFUCK_ARGUMENT_PLACEHOLDER $@
                ) && eval $TF_CMD;
                unset TF_HISTORY;
                export PYTHONIOENCODING=$TF_PYTHONIOENCODING;
                test -n "$TF_CMD" && print -s $TF_CMD
            }

# switch caps and escape permanently
if [[ -f /usr/bin/setxbmap ]]; then
    setxkbmap -option caps:escape
fi

# FileSearch
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -r . }

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }

# ALIASES
# Use vim for editing config files
alias zshconfig="vim ~/.zshrc"

alias g="git "
alias gc="git commit -am "
alias gs="git status"

# open multiple files in vim as tabs
alias vim="vim -p"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
#!/bin/zsh
source $ZSH/oh-my-zsh.sh


# Set name of the theme to load.
ZSH_THEME="theunraveler"
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git colored-man colorize virtualenv pip python brew osx zsh-syntax-highlighting)
plugins=(history-substring-search common-aliases compleat docker gitfast sublime sudo) 