# Default PATH
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

# Homebrew to PATH
export PATH="/opt/homebrew/bin:$PATH"

# Set vim as the default editor
VISUAL=vim; export VISUAL EDITOR=vim; export EDITOR=vim
# Set locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Set vim as the default editor
VISUAL=vim; export VISUAL EDITOR=vim; export EDITOR=vim


# switch caps and escape permanently
if [[ -f /usr/bin/setxbmap ]]; then
    setxkbmap -option caps:escape
fi

# FileSearch
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -r . }

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }

# ALIASES
# Use vim for editing config files
alias zshconfig="vim ~/.zshrc"

alias g="git "
alias gc="git commit -am "
alias gs="git status"

# open multiple files in vim as tabs
alias vim="vim -p"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval "$(starship init zsh)"

eval 
            fuck () {
                TF_PYTHONIOENCODING=$PYTHONIOENCODING;
                export TF_ALIAS=fuck;
                export TF_SHELL_ALIASES=$(alias);
                export TF_HISTORY="$(fc -ln -10)";
                export PYTHONIOENCODING=utf-8;
                TF_CMD=$(
                    thefuck THEFUCK_ARGUMENT_PLACEHOLDER $@
                ) && eval $TF_CMD;
                unset TF_HISTORY;
                export PYTHONIOENCODING=$TF_PYTHONIOENCODING;
                test -n "$TF_CMD" && print -s $TF_CMD
            }