
[font]
size = 12

[window.padding]
x = 5
y = 0 

[font.normal]
family = 'Hack Nerd Font'

[window]
opacity = 0.80
blur = true

[env]
TERM = 'xterm-256color'

[general]
import = [
    "~/.config/alacritty/themes/themes/nordic.toml"
]
